# Generated by Django 6.1 on 2026-08-13 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('EXCHANGE_CONTACTED', 'Exchange Contacted'), ('RECOVERY_IN_PROGRESS', 'Recovery in Progress'), ('RECOVERED', 'Recovered - Fee Due'), ('CLOSED', 'Closed'), ('UNRECOVERABLE', 'Unrecoverable')], default='PENDING_REVIEW', max_length=30)),
                ('scam_category', models.CharField(choices=[('FAKE_INVESTMENT', 'Fake Investment Platform'), ('ROMANCE', 'Romance Scam'), ('IMPERSONATION', 'Impersonation of Authority'), ('PHISHING', 'Phishing'), ('FAKE_JOB', 'Fake Job Offer'), ('CRYPTO_RUGPULL', 'Crypto Rugpull'), ('BANK_WIRE_FRAUD', 'Bank Wire Fraud'), ('OTHER', 'Other')], max_length=30)),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('recovery_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('transaction_method', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('BANK_WIRE', 'Bank Wire'), ('CREDIT_CARD', 'Credit Card'), ('GIFT_CARD', 'Gift Cards'), ('OTHER', 'Other')], max_length=20)),
                ('transaction_data', models.JSONField(default=dict)),
                ('first_transaction_date', models.DateField()),
                ('last_transaction_date', models.DateField()),
                ('narrative', models.TextField(max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.case')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('PHONE', 'Phone')], default='EMAIL', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='cases.case')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_communications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('SCREENSHOT', 'Screenshot'), ('BANK_STATEMENT', 'Bank Statement'), ('EMAIL', 'Email Headers'), ('CHAT_LOG', 'Chat Log'), ('TRANSACTION_LOG', 'Transaction Log'), ('OTHER', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
            ],
            options={
                'db_table': 'internal_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
